### PR TITLE
Adds editing to types

### PR DESCRIPTION
**Pull request by phila413**
Types are now available to edit on both gui and cli.  To edit on cli use the command "settype <attribute>..." (or look at the help).  The datastructure was changed pretty similar to how changeVis was made (just with types obviously).  Also, made tests for the changeType functions in the model (and covered a few more cases in the CLIView).

### CODE REVIEW

**Review by SerbianSensation — COMMENTED** [review]
Looks good to me, nice work! Only thing I would comment on is that when you hit cancel on a class in edit mode, it resets the classes to position to the top left (0,0). Idk if this is intended behavior or not, it was kind of annoying having to move my mouse to have to click the class again, or to drag it around.

**Review by SerbianSensation — COMMENTED** [review]
An additional comment, for the CLI I see that settype is now a command, so I might try to add tab completion for that quick, then we can merge that all together. Let me know if that is something you don't want me to do or don't want to wait on.

**Comment by phila413** [comment]
> 
> 
> Looks good to me, nice work! Only thing I would comment on is that when you hit cancel on a class in edit mode, it resets the classes to position to the top left (0,0). Idk if this is intended behavior or not, it was kind of annoying having to move my mouse to have to click the class again, or to drag it around.

Yeah that's weird and totally shouldn't be intended.  I'll have to look into that before we push that into develop.  It probably comes from something I changed with the controller simplification branch

**Review by SerbianSensation — APPROVED** [review]
Nice and simple fix, looks good to me!

**Pull request merged**
