### PR TITLE
Fixes Label bug

### PR DESCRIPTION
**Pull request by phila413**
- Fixes a bug when the user deletes the last field in a class, but the "Visibility Type Name" Label doesn't move back to the left because the field got deleted after the function call.
 - Fixes a bug were the labels don't look good in other operating systems
 - Adds more tests

### CODE REVIEW

**Review by SerbianSensation — COMMENTED** [review]
When I go to add a field, putting in a type name plus a space, then tab and putting in a field name, then hitting plus displays the message "Cannot add field." 
I tried on an older version and it seems like this didn't happen before.

To replace what I did, try this:
Type: String (hit space then tab)
Name: fieldName

Hit plus.

**Comment by phila413** [comment]
> 
> 
> When I go to add a field, putting in a type name plus a space, then tab and putting in a field name, then hitting plus displays the message "Cannot add field."
> I tried on an older version and it seems like this didn't happen before.
> 
> To replace what I did, try this:
> Type: String (hit space then tab)
> Name: fieldName
> 
> Hit plus.

Correct.  This is one of the bugs we fixed in the pr right before the presentation.  You shouldn't be able to have spaces in types or names.  Think about it like in code.  You can't say "int my Variable = 0;" or " dou ble myVariable = 0;"  Types can only be one word, just like classes (since types can also be classes), at least as far as I know.

**Comment by SerbianSensation** [comment]
> > When I go to add a field, putting in a type name plus a space, then tab and putting in a field name, then hitting plus displays the message "Cannot add field."
> > I tried on an older version and it seems like this didn't happen before.
> > To replace what I did, try this:
> > Type: String (hit space then tab)
> > Name: fieldName
> > Hit plus.
> 
> Correct. This is one of the bugs we fixed in the pr right before the presentation. You shouldn't be able to have spaces in types or names. Think about it like in code. You can't say "int my Variable = 0;" or " dou ble myVariable = 0;" Types can only be one word, just like classes (since types can also be classes), at least as far as I know.

I'm just confused because I did not put anything after the space. I guess the behavior I expected was that it would trim it down to just "String", removing the space. Maybe we just need to add a .trim() somewhere.

**Comment by phila413** [comment]
> 
> 
> > > When I go to add a field, putting in a type name plus a space, then tab and putting in a field name, then hitting plus displays the message "Cannot add field."
> > > I tried on an older version and it seems like this didn't happen before.
> > > To replace what I did, try this:
> > > Type: String (hit space then tab)
> > > Name: fieldName
> > > Hit plus.
> > 
> > 
> > Correct. This is one of the bugs we fixed in the pr right before the presentation. You shouldn't be able to have spaces in types or names. Think about it like in code. You can't say "int my Variable = 0;" or " dou ble myVariable = 0;" Types can only be one word, just like classes (since types can also be classes), at least as far as I know.
> 
> I'm just confused because I did not put anything after the space. I guess the behavior I expected was that it would trim it down to just "String", removing the space. Maybe we just need to add a .trim() somewhere.

Oh ok, yeah the code we did in that pr doesn't handle anything like that.  Personally, I don't think it should do that, kinda seems weird to automatically start messing around with the stuff they want to be put in the model.  Like usually when filling out forms on the internet websites just throw errors and don't fix it themselves I feel like.  Anyways though, I don't think that should be an issue to fix in this pr, and should be in a new one.

**Comment by SerbianSensation** [comment]
> > > > When I go to add a field, putting in a type name plus a space, then tab and putting in a field name, then hitting plus displays the message "Cannot add field."
> > > > I tried on an older version and it seems like this didn't happen before.
> > > > To replace what I did, try this:
> > > > Type: String (hit space then tab)
> > > > Name: fieldName
> > > > Hit plus.
> > > 
> > > 
> > > Correct. This is one of the bugs we fixed in the pr right before the presentation. You shouldn't be able to have spaces in types or names. Think about it like in code. You can't say "int my Variable = 0;" or " dou ble myVariable = 0;" Types can only be one word, just like classes (since types can also be classes), at least as far as I know.
> > 
> > 
> > I'm just confused because I did not put anything after the space. I guess the behavior I expected was that it would trim it down to just "String", removing the space. Maybe we just need to add a .trim() somewhere.
> 
> Oh ok, yeah the code we did in that pr doesn't handle anything like that. Personally, I don't think it should do that, kinda seems weird to automatically start messing around with the stuff they want to be put in the model. Like usually when filling out forms on the internet websites just throw errors and don't fix it themselves I feel like. Anyways though, I don't think that should be an issue to fix in this pr, and should be in a new one.

Alright, that sounds good. Don't wanna force a change but figured I'd throw it out there.

**Review by SerbianSensation — APPROVED** [review]
On another note, testing the GUI, I did not run into any of the bugs you guys have mentioned. Good work!

**Pull request merged**
