### PR TITLE
Adds a scrollBar and fixes margin bug in htmlBox

### PR DESCRIPTION
**Pull request by phila413**
- Adds a scrollBar to GUI to allow for bigger UMLs (both vertical and horizontal scroll bars)
 - Fixes a bug where a field/method/parameter name gets put on a new line away from its visibility and type
 - Changes htmlBox and editBox to HtmlBox and EditBox to adhere to java conventions

### CODE REVIEW

**Review by SerbianSensation — COMMENTED** [review]
Looks good to me! Only thing I would maybe comment on is that vertical scrolling is very slow when using the mouse scroll, is there a way to change the speed and make it faster?

**Comment by SerbianSensation** [comment]
> Looks good to me! Only thing I would maybe comment on is that vertical scrolling is very slow when using the mouse scroll, is there a way to change the speed and make it faster?

Follow up: looks like this might work: https://stackoverflow.com/questions/5583495/how-do-i-speed-up-the-scroll-speed-in-a-jscrollpane-when-using-the-mouse-wheel

**Comment by phila413** [comment]
> 
> 
> > Looks good to me! Only thing I would maybe comment on is that vertical scrolling is very slow when using the mouse scroll, is there a way to change the speed and make it faster?
> 
> Follow up: looks like this might work: https://stackoverflow.com/questions/5583495/how-do-i-speed-up-the-scroll-speed-in-a-jscrollpane-when-using-the-mouse-wheel

Neat.  It did make it faster! I'll add it in

**Review by SerbianSensation — APPROVED** [review]
Pane scrolls at a nice speed now, good stuff!

**Pull request merged**
