### PR TITLE
JLine stuff

### PR DESCRIPTION
**Pull request by HomelessSkittle**
Tab Completion! 

Realistically, not too many changes required, and all under CLI.

### CODE REVIEW

**Review by SerbianSensation — COMMENTED** [review]
Good work on the tab completion! Only thing is there still is that bug where when you try to quit with unsaved changes, the program goes derp and you almost have to brute force it. Hopefully that is a quick fix and would be nice to resolve.

**Comment by ianreger** [comment]
Tab completion is working so well! I was wondering if we wanted to add tab completion for each relationship type as well as keeping them capitalized. Otherwise, works great!

**Comment by HomelessSkittle** [comment]
For the future, I plan on creating different completers/readers, because at present, at any point and time the user has access to the full library of possible tab completions, even if they aren't applicable.

**Comment by SerbianSensation** [comment]
> For the future, I plan on creating different completers/readers, because at present, at any point and time the user has access to the full library of possible tab completions, even if they aren't applicable.

Good idea, that's something I noticed too.

**Review by SerbianSensation — APPROVED** [review]
Everything should be working now, merge time.

**Pull request merged**
