### PR TITLE
Change Code Coverage tests

### PR DESCRIPTION
**Pull request by SerbianSensation**
Hopefully this will get rid of the check for differences between patches, something that is unnecessary and would usually fail.

### CODE REVIEW

**Review by SerbianSensation — COMMENTED** [review]
So doesn't seem like it changed it... but it does not fail the CI if it doesn't pass. Plus limited the checks to be done only on pull_requests and pushes to develop instead of literally every single push.

**Comment by willkill07** [comment]
@SerbianSensation I also removed the `codecov/patch` from being a restriction / necessary pass when submitting PRs. This may also resolve it 🤷

**Comment by willkill07** [comment]
I really don't think you only want it to run on develop. It's important that CI runs on PRs as well.

**Comment by willkill07** [comment]
@SerbianSensation check out the codecov documentation: https://docs.codecov.io/docs/commit-status#disabling-a-status

**Review by HomelessSkittle — APPROVED** [review]
Looks good to me

**Pull request merged**
