### PR TITLE
Refactored code to follow an MVC format

### PR DESCRIPTION
**Pull request by JohnHynes**
Summary
 - Split Controller into CLIController and GUIController
 - Models are now contained in controllers rather than views

### CODE REVIEW

**Comment by JohnHynes** [comment]
So far I think this is all looking very good. It might be ready to merge after a couple more pass-overs just to make sure there are no more big bugs or anything. I don't think there are any more big changes that need to happen on this branch unless there's something else you guys can think of that is vital to the MVC refactor. I know writing more tests is on the list but after that I think we're ready.

**Review by SerbianSensation — COMMENTED** [review]
Looking good! Only thing I found that I feel like we should change is that when you do the 'list' command, then try to quit or load another file, it warns about unsaved changes, even though the list command does not change anything.

I am going to work on splitting up the tests like we discussed, so let me know if you want me to try to change that behavior while I'm at it. Other than that, looks great!

**Review by phila413 — APPROVED** [review]
I couldn't find any bugs in the GUI nor the CLI, so it looks good to me!

**Review by SerbianSensation — APPROVED** [review]
Added the tests and I changed the behavior of the list command, so to me, it looks good as well!

**Review by ianreger — COMMENTED** [review]
Code changes look great. Ran and tested the gui and cli and everything seems to be working as intended.

**Pull request merged**
